[general]
import = [
  "catppuccin-mocha.toml",
]

[window]
padding.x = 3
padding.y = 3

[font]
normal = { family = "Iosevka Nerd Font Mono", style = "Light" }
bold = { family = "Iosevka Nerd Font Mono", style = "Light" }
italic = { family = "Iosevka Nerd Font Mono", style = "Light" }
size = 13

# [colors]
# cursor = { cursor = "#ff0000" }

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
    { key = "Enter", mods = "Command", action = "ToggleSimpleFullscreen" },
]
