[settings]
show_help = false
selected_filter = "work"
updated_at_cut_off = "2023-12-01T00:00:00Z"

[filters]
axum = [
    "tokio-rs/axum",
    "ibraheemdev/matchit",
]
not-work = [
    "-EmbarkStudios",
    "-KhronosGroup/MoltenVK",
]
work = [
    "EmbarkStudios",
    "KhronosGroup/MoltenVK",
]
