[global_except.terminal]
exclude_apps = ["Ghostty"]

[[global_except.terminal.shortcuts]]
from = "ctrl+w"
to = "opt+delete"

[[global_except.terminal.shortcuts]]
from = "ctrl+j"
to = "down"

[[global_except.terminal.shortcuts]]
from = "ctrl+k"
to = "up"

[[global_except.terminal.shortcuts]]
from = "ctrl+h"
to = "left"

[[global_except.terminal.shortcuts]]
from = "ctrl+l"
to = "right"

[apps.slack]
match = "Slack"

[[apps.slack.shortcuts]]
from = "ctrl+n"
to = "down"

[[apps.slack.shortcuts]]
from = "ctrl+p"
to = "up"
