[Personal]
source        = imaps://david.pdrsn%40gmail.com:***REMOVED***@imap.gmail.com:993
outgoing      = smtp://david.pdrsn%40gmail.com:***REMOVED***@smtp.gmail.com:587
default       = GitHub
from          = David Pedersen <david.pdrsn@gmail.com>
cache-headers = true
folders = INBOX, GitHub, Archive, [Gmail]/All Mail, [Gmail]/Drafts, [Gmail]/Sent Mail, [Gmail]/Trash
folders-sort = INBOX, GitHub, Archive, [Gmail]/All Mail, [Gmail]/Drafts, [Gmail]/Sent Mail, [Gmail]/Trash
check-mail = 5m
