#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

source ./scripts/lib/parallel-tasks.sh

start_task "local" just switch
start_task "vps-1" just switch-vps-1
start_task "vps-2" just switch-vps-2

wait_for_tasks
