export PATH=$PATH:/Users/davidpdrsn/.cargo/bin
export PATH=$PATH:/Users/davidpdrsn/.bin

# open atuin with ctrl-p
bindkey '^p' atuin-up-search

# make completion with tab look not terrible
setopt auto_menu
setopt always_to_end
setopt complete_in_word
unsetopt flow_control
unsetopt menu_complete
zstyle ':completion:*:*:*:*:*' menu select
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'
zstyle ':completion::complete:*' use-cache 1
zstyle ':completion::complete:*' cache-path $ZSH_CACHE_DIR
zstyle ':completion:*' list-colors ''
zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#) ([0-9a-z-]#)*=01;34=0=01'

## PROMPT
## -----------------------

# Make the colors work
autoload -U colors && colors

# edit current line in vim
if [[ -z "$NVIM" ]]; then
  autoload -U edit-command-line
  zle -N edit-command-line
  bindkey '\033' edit-command-line
  export KEYTIMEOUT=1
fi

# Allow for output of commands
setopt prompt_subst

local symbol="❯"
local start="%(?,%{$fg[green]%}$symbol%{$reset_color%},%{$fg[red]%}$symbol%{$reset_color%})"

# Function to check if we are in a nix shell
is_in_nix_shell() {
  if [ -n "$IN_NIX_SHELL" ]; then
    echo "[nix] "
  fi
}

PROMPT=$'
$(smart-pwd-2) $(is_in_nix_shell)%{$reset_color%}$(git-prompt)$(is-vim-running)%{$reset_color%}
${start} '
RPROMPT=$''

## ALIASES
## -----------------------

alias ..='z ..'
alias c='clear'
alias ca='cargo'
alias cd='z'
alias cat='bat'
alias dt='cd ~/Desktop'
alias diff='diff --color'
alias ea='cd ~/config && nvim ~/config/configuration.nix'
alias rl='source ~/.zshrc'
alias l='exa --long --header --git --all --sort name'
alias la='exa -a --long --header --sort name'
alias mkdir='mkdir -p'
alias xtask='cargo xtask'
alias o='open .'
alias b='/Users/davidpdrsn/.cargo/bin/t build'
alias r='/Users/davidpdrsn/.cargo/bin/t run'
alias tl='ingestlogs pipe --'
alias ci='/Users/davidpdrsn/.cargo/bin/t "open ci"'
alias wim='/Applications/wim-dev.app/Contents/MacOS/ark-client'
alias wim-app='/Applications/wim-dev.app/Contents/MacOS/ark-client'
alias commit-config='cd ~/config && git add --all && git commit -m "misc changes" && git push && cd -'
alias at='tmux attach'
alias local-ark-client='/Users/davidpdrsn/code/embark/wim-app/wim-app/target/release/ark-client'
alias mbark='/Users/davidpdrsn/code/embark/wim-mod/mbark'
alias godot='/Applications/Godot_mono.app/Contents/MacOS/Godot'
alias x='/Users/davidpdrsn/code/bits-n-wires/x'
alias blender='/Applications/Blender.app/Contents/MacOS/Blender'
alias ds='t "darwin-rebuild switch"'
alias dbui='nvim +DBUI'
alias format-lua='stylua --config-path ~/.stylua.toml $(fd .lua)'
alias claude-json='claude --print --output-format json'
alias claude-yolo='claude --dangerously-skip-permissions'

# nvim
alias vi='nvim'
alias vim='nvim'
alias vimconflicts='nvim $(rg -l -. "[<>=]{7}")'
alias vv='nvim $(rg --files | fzf)'

# git
alias gaa='git add --all'
alias gac='git add --all && git commit --verbose'
alias gap='git add -p'
alias gb='git branch'
alias gc='git commit --verbose'
alias gcai='git commit --verbose -e -m "$(git-diff-ai-summarize)"'
alias gco='git checkout'
alias gcob='git checkout -b'
alias gcof='git-branch-picker checkout'
alias gmf='git-branch-picker merge'
alias git-cargo-lock-conflict='git checkout main -- Cargo.lock'
alias gl='git log --decorate --oneline -20'
alias gll='git log --decorate --oneline'
alias ggl='git log --decorate --oneline -20'
alias ggll='git log --decorate --oneline'
alias gp='git push'
alias gpf='git push --force-with-lease'
alias gd='git diff'
alias d='git diff'
alias gdc='git diff --cached'
alias gr='git reset'
alias grh='git reset --hard'
alias grs='git reset --soft'
alias gca='git commit --amend --verbose'
alias gpr='cargo fmt -- --check && gh pr create'
alias gpll='git pull'
alias ga='git add'
alias grb='git rebase'
alias gm='git merge'
alias grbc='git rebase --continue'
alias grba='git rebase --abort'
alias grbi='git rebase -i'
alias gs='git show'
alias gg='lazygit'

## FUNCTIONS
## -----------------------

function g {
  if [[ $# > 0 ]]; then
    git $@
  else
    git status -sb
  fi
}
compdef g=git

function v {
  if [[ $# > 0 ]]; then
    nvim $@
  else
    nvim
  fi
}

function take() {
  mkdir -p "$1"
  cd "$1"
}
